lane :bonjour do

  scan(
    code_coverage: true
  )
  xcov

#  if UI.confirm("Sure ?")
#    UI.success "Coooooooool !"
#  else
#    UI.error "Hmmm ?"
#  end

end

lane :deploy do

  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "ridergoster/fastlane-demo-moc2",
      name: version, #nom de la version sur Github
      tag_name: "v#{version}",
      description: changelog_from_git_commits(),
      commitish: "master"
    )

  end

end
